### PR TITLE
 #479 - add document_status - calculated

### PR DESCRIPTION
**Pull request by lkolacz**

### CODE REVIEW

**Comment by lkolacz** [comment]
@elyk updates on front-end needed - field changed from `status` to `document_status`

**Comment by elyk** [comment]
@lkolacz what does `document` refer to?

**Comment by lkolacz** [comment]
@elyk I could call it also `eoi_status` .. didn't know what name to take... the best
I'm open to change it to `status` as a property and remove model attribute and don't storage it..

**Comment by elyk** [comment]
Ok. That is the best/most straight-forward way. Then we will add boolean `is_completed` correct?

**Comment by lkolacz** [comment]
@elyk I guess we don't need to have these field in db as well ....
if we post to EOI-Update endpoint field `completed_reason` , the we can set (the reason and `completed_date`) and this is an information for us if it is completed or not
and update property from this:
```
    @property
    def is_completed(self):
        return self.completed_reason is not None
```
to this
```
    @property
    def is_completed(self):
        return self.completed_reason is not None and self. completed_date is not None
```

What do You think about it?

**Comment by elyk** [comment]
@lkolacz I think it's a good idea, but would like to still store `is_completed` separately if for any reason `completed_reason` becomes optional in the future. Think it's the safest way.

**Comment by marcindo** [comment]
This will require change in FE as I'm sending project patch with `status: 'Com'`, so please provide new field name that needs to be send

**Comment by lkolacz** [comment]
@marcindo You should skip status, `completed_reason` if will be set first time, backend will update flag `is_completed` add `completed_date` to today...
field `status` from now will be a calculated property that check flag `is_completed` and `deadline date`
@elyk Kyle, please make a last code review ... should be fine after our discussion ... :)

**Pull request merged**
